categories:
  - title: '🏗 Infrastructure'
    labels:
      - 'infrastructure'
      - 'performance'
      - 'perf'
  - title: '💰 Growth'
    labels:
      - 'growth'
      - 'core'
  - title: 'Personalized Adaptive Learing'
    labels:
      - 'AI'
      - 'Adaptive Learning'
  - title: '🔍 SEO'
    label: 'seo'
  - title: '⚙️ Execution Engine'
    label: 'execution-engine'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🕵🏻‍♂️ Sentry'
    label: 'sentry'
  - title: '🧪 Tests'
    label: 'tests'
  - title: '🧰 Maintenance'
    label: 'maintenance'
  - title: '🖱 UX'
    label: 'UX'
  - title: '🧹 Code Cleanup'
    label: 'code-cleanup'
  - title: '⚠️ Livesite'
    labels:
      - 'livesite'
      - 'on-call'
  - title: '🎢 Migrations'
    labels:
      - 'run-migration'
      - 'blocking-migration'
      - 'run-script'
  - title: 'Deploy Collaborative Editor'
    label: 'deploy-collaborative-editor'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  # Change Log

  $CHANGES

  ## Contributors
  $CONTRIBUTORS
